name: Spider

on:
  push:
    branches: [ master ]
  #schedule:
  #- cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    
    - name: Download procyon-decompiler
      run: wget https://bitbucket.org/mstrobel/procyon/downloads/procyon-decompiler-0.5.36.jar -o ./procyon-decompiler.jar
    
    - name: Run procyon-decompiler
      run: java -jar procyon-decompiler.jar
      
