name: Spider

on:
  push:
    branches: [ master ]
  #schedule:
  #- cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    
    - name: Download cfr
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: leibnitz27/cfr
        tag: '0.150'
        file: cfr-0.150.jar
    
    - name: Run spider
      run: ./scripts/spider.ps1
      shell: pwsh
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      
